version: '{build}'

branches:
  only:
    - master
    
os: Visual Studio 2015

environment:
  matrix:
  - COMPILER: msvc2015
    PLATFORM: x64
    CONFIGURATION: Debug
    MSYS2_ARCH: x86_64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64
    BIT: 64
    BUILDTOOL: msbuild

install:
  - set
  - '%APPVEYOR_BUILD_FOLDER%\ci\appveyor\install.bat'
  
build_script:
  - '%APPVEYOR_BUILD_FOLDER%\ci\appveyor\build.bat'

deploy:
- provider: FTP
  host: ftp.cadwork.ch
  protocol: ftps
  username: ftproot
  password:
    secure: ZrkE2pFABFhoIHDq50LCiA==
  folder: /public/Baldaccini
